- psalm-baseline.xml
- src/Application/MappingRepository.php
- src/MappingListSerializer.php
- src/Persistence/ContentSlotMappingRepository.php
- src/Persistence/InMemoryEntityContentRepository.php
- src/Persistence/InMemoryMappingRepository.php
- src/Persistence/SlotEntityContentRepository.php
- tests/Persistence/ContentSlotMappingRepositoryTest.php
- tests/Persistence/InMemoryMappingRepositoryUnitTest.php
- tests/Persistence/SlotEntityContentRepositoryTest.php
Fixes https://github.com/ProfessionalWiki/WikibaseRDF/issues/6
> Finish ContentSlotMappingRepository implementation

- Makefile
- extension.json
- i18n/en.json
- phpstan-baseline.neon
- phpstan.neon
- psalm-baseline.xml
- resources/ext.wikibase.rdf.js
- resources/ext.wikibase.rdf.less
- src/Application/ShowMappingsUseCase.php
- src/Hooks.php
- src/Persistence/StubMappingRepository.php
- src/Presentation/MappingsPresenter.php
- src/Presentation/StubMappingsPresenter.php
- src/WikibaseRDFExtension.php
Part of #4
Adds initial wiring to get Mappings through to the page.
Adds JS for the collapse toggler, but no interaction yet.
Very minimal CSS.
> Initial Stub UI

- src/Application/Mapping.php
- src/Presentation/RDF/MappingRdfBuilder.php
- tests/Application/MappingTest.php
- tests/Persistence/ContentSlotMappingRepositoryTest.php
For https://github.com/ProfessionalWiki/WikibaseRDF/issues/8
> Add MappingRdfBuilder stub

- extension.json
- src/Hooks.php
- src/Presentation/RDF/MappingRdfBuilder.php
- src/Presentation/RDF/MultiEntityRdfBuilder.php
- src/WikibaseRDFExtension.php
Part of https://github.com/ProfessionalWiki/WikibaseRDF/issues/8
> Append mappings to the RDF output

- psalm-baseline.xml
- psalm.xml
- src/Hooks.php
- src/WikibaseRdfExtension.php
- tests/Presentation/StubMappingsPresenterTest.php
> Initial Stub UI cleanup

- src/EntryPoints/MediaWikiHooks.php
Fixes #41 
For dev purposes this requires a DB reset.
> Hide RDF slot

- src/EntryPoints/MediaWikiHooks.php
Fixes https://github.com/ProfessionalWiki/WikibaseRDF/issues/47
> Use the correct EntityId to get mappings

- i18n/qqq.json
> Add system message documentation

- src/EntryPoints/Rest/GetMappingsApi.php
- tests/EntryPoints/Rest/GetMappingsApiTest.php
Fixes #32
Fixes #31 
Replaces #52 
Added some tests and minimal refactor of GetMappingsApi. A future refactor can add a dedicated Presenter class.
> Add GetMappingsApi tests

- i18n/en.json
- i18n/qqq.json
- phpstan-baseline.neon
- psalm-baseline.xml
- src/Application/EntityMappingsAuthorizer.php
- src/Application/MappingRepository.php
- src/Application/SaveMappings/SaveMappingsPresenter.php
- src/Application/SaveMappings/SaveMappingsUseCase.php
- src/Application/ShowMappingsUseCase.php
- src/EntryPoints/Rest/SaveMappingsApi.php
- src/Persistence/EntityContentRepository.php
- src/Persistence/SlotEntityContentRepository.php
- src/Persistence/UserBasedEntityMappingsAuthorizer.php
- src/Presentation/MappingsPresenter.php
- src/Presentation/RestSaveMappingsPresenter.php
- src/Presentation/StubMappingsPresenter.php
- src/WikibaseRdfExtension.php
- tests/Application/SaveMappings/SaveMappingsUseCaseTest.php
- tests/EntryPoints/Rest/GetMappingsApiTest.php
- tests/EntryPoints/Rest/SaveMappingsApiTest.php
- tests/Persistence/UserBasedEntityMappingsAuthorizerTest.php
- tests/Presentation/StubMappingsPresenterTest.php
- tests/TestDoubles/FailingEntityMappingsAuthorizer.php
- tests/TestDoubles/SpySaveMappingsPresenter.php
- tests/TestDoubles/SucceedingEntityMappingsAuthorizer.php
Fixes #65
Refs https://github.com/ProfessionalWiki/WikibaseRDF/pull/64#pullrequestreview-1064134628
UI with permission:
UI without permission:
Command line (without anonymous permission):
> Add authorizer to UI and Use Case

- i18n/en.json
- i18n/qqq.json
- src/EntryPoints/MediaWikiHooks.php
Refs https://github.com/ProfessionalWiki/WikibaseRDF/issues/71#issuecomment-1209898209
Something like this?
> Add config form intro text

- README.md
- docs/rest.md
> Add initial API docs

- src/EntryPoints/MediaWikiHooks.php
- src/Presentation/HtmlMappingsPresenter.php
- src/WikibaseRdfExtension.php
- tests/Presentation/HtmlMappingsPresenterTest.php
> Hide edit links on diff page

- i18n/en.json
- src/EntryPoints/MediaWikiHooks.php
> Add plural message

- src/Application/PredicateList.php
- tests/Application/PredicateListTest.php
Fixes https://github.com/ProfessionalWiki/WikibaseRDF/issues/88
> Remove duplicate predicate definitions

- phpstan-baseline.neon
- psalm-baseline.xml
- src/Application/Mapping.php
- src/Application/ObjectValidator.php
- src/Application/SaveMappings/SaveMappingsUseCase.php
- src/Application/WikibaseUrlObjectValidator.php
- src/WikibaseRdfExtension.php
- tests/Application/MappingTest.php
- tests/Application/SaveMappings/SaveMappingsUseCaseTest.php
- tests/Application/WikibaseUrlObjectValidatorTest.php
- tests/EntryPoints/Rest/SaveMappingsApiTest.php
- tests/Persistence/ContentSlotMappingRepositoryTest.php
- tests/TestDoubles/FailingObjectValidator.php
- tests/TestDoubles/SucceedingObjectValidator.php
Refs #95
UI:
API:
```shell
curl -X POST -H 'Content-Type: application/json' "http://localhost:8484/rest.php/wikibase-rdf/v0/mappings/Q1"   -d '[{"predicate": "owl:sameAs", "object": "http://www.w3.org/2000/01/rdf-schema#subClassOf"}, {"predicate": "rdfs:subClassOf", "object": "foo:Bar"}]'
```
> Add URL validation

- i18n/en.json
> Rename relation to predicate

- src/MappingListSerializer.php
> Extract mappingFromArray method

- psalm-baseline.xml
- src/Presentation/RDF/MappingRdfBuilder.php
- src/Presentation/RDF/PropertyMappingPrefixBuilder.php
- src/WikibaseRdfExtension.php
- tests/Presentation/RDF/PropertyMappingPrefixBuilderTest.php
> Add config-based predicate mapping prefix

- README.md
- i18n/en.json
> WIP Reword label

- README.md
- i18n/en.json
Reverts ProfessionalWiki/WikibaseRDF#113
> Revert "WIP Reword label"

- resources/ext.wikibase.rdf.js
Refs #77
Some minor issues reported by ESLint.
We still have some hard errors left which prevent us from running this as part of CI:
> Fix some lint issues

- extension.json
- i18n/en.json
- i18n/qqq.json
- resources/ext.wikibase.rdf.js
- src/EntryPoints/MediaWikiHooks.php
> Add initial property edit popup

- src/EntryPoints/MediaWikiHooks.php
> Update addModules to array format
