ProfessionalWiki/WikibaseRDF

README.md
extension.json
phpstan-baseline.neon
psalm-baseline.xml
src/EntryPoints/Rest/SaveMappingsApi.php
src/Presentation/StubMappingsPresenter.php
src/WikibaseRdfExtension.php
tests/Presentation/StubMappingsPresenterTest.php

First part of #36 
This adds the config variable and displays it in the stub UI.
Follow-ups before completing #36:
* add allowed predicate validation (possibly pending https://github.com/ProfessionalWiki/WikibaseRDF/discussions/36)
* add API error handling to see the validation outcome (https://github.com/ProfessionalWiki/WikibaseRDF/issues/33)

Add initial predicate configuration

---

i18n/en.json
psalm.xml
src/Application/SaveMappings/SaveMappingsPresenter.php
src/Application/SaveMappings/SaveMappingsUseCase.php
src/EntryPoints/Rest/GetMappingsApi.php
src/EntryPoints/Rest/SaveMappingsApi.php
src/Presentation/RestSaveMappingsPresenter.php
src/WikibaseRdfExtension.php
tests/Application/SaveMappings/SaveMappingsUseCaseTest.php
tests/EntryPoints/Rest/GetMappingsApiTest.php
tests/EntryPoints/Rest/SaveMappingsApiTest.php
tests/Presentation/StubMappingsPresenterTest.php
tests/TestDoubles/SpySaveMappingsPresenter.php
tests/TestDoubles/ThrowingMappingRepository.php

Primarily part of #33
Follow up to #38/#27 by adding allowed predicate validation and failure response.
Some comments below.

Add Save Mappings API response handling

---

src/MappingListSerializer.php
tests/WikibaseRdfIntegrationTest.php

From https://github.com/ProfessionalWiki/WikibaseRDF/pull/56#discussion_r933858751
Doing this as a separate branch/PR to figure out what's going on.
When only the one table (or none) is specified it seems to cause the issue with the wrong slot content being deserialized. With all the tables used in the query it no longer picks up the wrong rows.
Not sure if this means there's a chance the query might in some theoretical circumstance get the wrong data, or if the test environment DB setup was messing this up.

Add lookup tables

---

i18n/en.json
src/Application/SaveMappings/SaveMappingsPresenter.php
src/Application/SaveMappings/SaveMappingsUseCase.php
src/EntryPoints/Rest/SaveMappingsApi.php
src/MappingListSerializer.php
src/Presentation/RestSaveMappingsPresenter.php
src/WikibaseRdfExtension.php
tests/Application/SaveMappings/SaveMappingsUseCaseTest.php
tests/EntryPoints/Rest/SaveMappingsApiTest.php
tests/Persistence/SqlAllMappingsLookupTest.php
tests/TestDoubles/SpySaveMappingsPresenter.php
tests/WikibaseRdfIntegrationTest.php

From https://github.com/ProfessionalWiki/WikibaseRDF/pull/46#discussion_r930147474 and part of #31 
Is my understanding of that correct here?
* `SaveMappingsApi` validates:
* Entity ID string is in the URL
* Payload contains well-formed Json
* The UC validates:
* Entity ID is valid
* Entity ID exists
* Mapping predicates are well-formed
* Mapping predicates are in the allowed list
* Mapping object values

Refactor use case and Save API validation

---

.eslintrc.json
.stylelintrc.json
Gruntfile.js
extension.json
package.json
resources/ext.wikibase.rdf.js
resources/ext.wikibase.rdf.less
src/Presentation/StubMappingsPresenter.php
tests/EntryPoints/Rest/SaveMappingsApiTest.php

Add functional UI

---

resources/ext.wikibase.rdf.js
resources/ext.wikibase.rdf.less

Refs #60
Quick CSS solution to block click actions when Save/Remove is clicked. It prevents clicks and removes the link color:
For now this is primarily to prevent rapid (almost) concurrent Save/Remove clicks. When saving only a few mappings this is very quick so the disabling and color change is very brief. If we find a point where saving is too slow then we can add additional UI indicators (e.g. "Saving..." or a spinner).

Add simple CSS to block actions

---

src/Application/MappingRepository.php
src/Application/SaveMappings/SaveMappingsPresenter.php
src/Application/SaveMappings/SaveMappingsUseCase.php
src/EntryPoints/Rest/SaveMappingsApi.php
src/Persistence/EntityContentRepository.php
src/Persistence/SlotEntityContentRepository.php
src/Presentation/RestSaveMappingsPresenter.php
src/WikibaseRdfExtension.php
tests/Application/SaveMappings/SaveMappingsUseCaseTest.php
tests/EntryPoints/Rest/SaveMappingsApiTest.php
tests/TestDoubles/PermissionDeniedMappingRepository.php
tests/TestDoubles/SpySaveMappingsPresenter.php

Refs #45 
First stab at this. Not sure if this permission check is better off in the repo (like the PR) or in the UC. I imagine if the repo was used elsewhere we'd have to repeat the permission check. Thoughts?
I'm still trying to figure out how to use the MW API to get tokens and login via Curl. That's why I haven't updated the Readme yet.
----
LocalSettings:
```php
$wgGroupPermissions['*']['edit'] = false;
```
When you run:
```shell
curl -X POST -H 'Content-Type: application/json' "http://localhost:8484/rest.php/wikibase-rdf/v0/mappings/Q1" \
-d '[{"predicate": "owl:sameAs", "object": "http://wwww.w3.org/2000/01/rdf-schema#subClassOf"}]' | jq
```
You get this:
LocalSettings:
```php
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = false;
```
And then using …

Add Save Mappings API permission check

---

README.md

Refs #69.
This just updates the readme format.
`$wgWikibaseRdfPredicates` is the only config we have at the moment.

Update configuration in readme

---

resources/ext.wikibase.rdf.js

Refs #66 
After #65 we should theoretically only be getting our own error responses using `ResponseFactory::createLocalizedHttpError()`. The previous anonymous error message (from MW, not us) shouldn't happen because the UI won't show the edit actions when not allowed. This PR therefore handles the known response structure based on that response method.
---
I am not sure that the error message localization approach is correct, though.
With English defaults (and forced exception in the code):
Response:
With LocalSettings `$wgLanguageCode = 'de';`:
Response:
With LocalSettings `$wgLanguageCode = 'de';` and user language = French:
Response:
This seems to be because `createLocalizedHttpError()` returns only 'en' and the the value of `$wgLanguageCode`:
`EntryPoint::getTextFormatters()`:
`
I …

Show localized error message

---

README.md
tests/EntryPoints/Rest/SaveMappingsApiTest.php

Very quick follow up to https://github.com/ProfessionalWiki/WikibaseRDF/pull/64#pullrequestreview-1064093533
I took a slightly different approach by moving all of the request logic into a method.
Does this make it cleaner, or do you think it is more useful to have an explicit concept of a "valid request"?

Refactor save mappings API test

---

extension.json
i18n/en.json
i18n/qqq.json
psalm-baseline.xml
psalm.xml
src/DataAccess/CombiningMappingPredicatesLookup.php
src/DataAccess/LocalSettingsMappingPredicatesLookup.php
src/EntryPoints/MediaWikiHooks.php
src/Presentation/HtmlPredicatesPresenter.php
src/Presentation/PredicatesPresenter.php
src/WikibaseRdfExtension.php
tests/DataAccess/LocalSettingsMappingPredicatesLookupTest.php
tests/Presentation/HtmlPredicatesPresenterTest.php

Fixes #81
This displays the _combined_ predicates from LocalSettings and the page.
* Should we do that?
* Or show two lists?
* Or show only the predicates defined on the page?
----
With no predicates:
With one predicate:
With multiple predicates:
(Plural done for the same reason as #85)

Format the defined predicates

---

psalm-baseline.xml
src/Presentation/HtmlMappingsPresenter.php
src/Presentation/HtmlPredicatesPresenter.php

From #87 
Replaces calls to the global `wfMessage` with local functions.
This is the simplest way to not just suppress the warnings. Otherwise we need to inject an `IContextSource` which is going to complicate testing.

Fix suppressed CI warnings

---

Makefile
phpunit.xml.dist
tests/Persistence/SqlAllMappingsLookupPerformanceTest.php

Refs #61 
This is excluded from the normal unit tests because it takes ~15 minutes. There's probably a more efficient way to setup the test data, but this works for now.
This includes some arbitrary expected times based on my laptop's performance.
Run with:
```
make perf
```
Example:

Add performance tests

---

src/Presentation/RDF/MappingRdfBuilder.php

Fixes #93 
`text()` vs `is()` seems to be the "string" vs "thing" difference.
I believe using the full URL is fine when passing only the first parameter of `is()`. However, if we need to support the `foo:bar` syntax then we might need to also break up base and local like with the predicate.

Export things not strings

---

src/MappingListSerializer.php
tests/MappingListSerializerTest.php

Fixes #99 
Simple implementatin of an additional method.
One side-effect, although probably harmless, is once you edit the mappings again it's going to overwrite (i.e. remove) the invalid mapping.

Don't fail when retrieving invalid mappings

---

src/Presentation/RDF/MappingRdfBuilder.php

Refs #100 
This is the simplest implementation that produces the example output as per https://github.com/ProfessionalWiki/WikibaseRDF/discussions/98#discussioncomment-3692976.
There are two possible issues with this implementation, although they might not be critical.
**Duplicate node issue:**
This is caused because the original "empty" `wdt` node is created by Wikibase here:
https://github.com/wikimedia/Wikibase/blob/master/repo/includes/Rdf/PropertySpecificComponentsRdfBuilder.php#L143-L146
I cannot find a way to inject anything there and my understanding is the RDF output is a stream, so you can only append. However, the resultant ttl file validates on something like http://ttl.summerofcode.be/, so I don't know if this is really a problem.
**Configurability issue:**
It seems to be …

Add simple fix for Property RDF mappings

---

resources/ext.wikibase.rdf.js
src/Presentation/HtmlMappingsPresenter.php
tests/Presentation/HtmlMappingsPresenterTest.php

Fixes #103 
On initial page render `rel="nofollow"` is added, but when an edit is done it is not added because it's irrelevant until the page is reloaded.

Render object URL as link

---

resources/ext.wikibase.rdf.less

Refs #108 
The problem had to do with the `/w` vs `/wiki` base path.
This change is working locally, but we need to deploy it first to test it in production.

Use relative path for icons

---

.eslintrc.json
.github/workflows/ci.yml
resources/ext.wikibase.rdf.js
resources/ext.wikibase.rdf.less
src/Presentation/HtmlMappingsPresenter.php

Fixes #67 (in so far as it disables the one check that makes it fail).
The "no-jquery/no-class-state" rule's warning level must be removed in #77.
There are no functional changes here. This just fixes whatever ESLint and Stylelint complained about, excludng the above rule.

Make linting pass and add to CI

---

i18n/en.json

All edits to the property will cause the duplication issue, not just edits to the mappings.
For https://github.com/ProfessionalWiki/WikibaseRDF/issues/115

Use more correct description in warning message

---

resources/ext.wikibase.rdf.less

styles: Replace 'mediawiki.ui/variables' call with skin variables
Removing 'mediawiki.ui/variables.less' `@import`.  Alternative to going back to static color value would be new skin-aware 'mediawiki.skin.variables.less' standard. But that would result in a bump of minimum required MediaWiki core version to >= v1.41.0. As I don't know the use case of this extension too well, removing and replacing one color with a static value seems like the simpler way forward right now.
Bug: T332541
Depends-On: I04f9e48a1cf9dee915cf51e1e12b17ff0a595a06

Remove deprecated 'mediawiki.ui/variables.less' import
